name: ShellCheck
on: [push, pull_request]
jobs:
  ShellCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: |
            wget -O /opt/shellcheck-stable.linux.x86_64.tar.xz https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz
            tar xf /opt/shellcheck-stable.linux.x86_64.tar.xz -C /opt

      - name: Version
        run: /opt/shellcheck-stable/shellcheck --version

      - name: Checkout
        uses: actions/checkout@v5

      - name: Analysis
        run: /opt/shellcheck-stable/shellcheck motd-on-acid.sh
